solvers:
  - solver_id: powermodels_dc_opf_highs
    framework: PowerModels.jl
    task: dc_opf
    formulation: DCPPowerModel
    optimizer: HiGHS
  - solver_id: powermodels_ac_opf_ipopt
    framework: PowerModels.jl
    task: ac_opf
    formulation: ACPPowerModel
    optimizer: Ipopt
  - solver_id: exago_scopflow_ipopt
    framework: ExaGO
    task: scopf
    formulation: SCOPFLOW
    optimizer: Ipopt
  - solver_id: pandapower_ac_opf_ipopt
    framework: pandapower
    task: ac_opf
    formulation: AC_OPF
    optimizer: Ipopt
